### ISSUE TITLE
Migrate content from data2health/nlp-sandbox-data-node-schemas

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox-schemas#2]
The repo [data2health/nlp-sandbox-data-node-schemas](https://github.com/data2health/nlp-sandbox-data-node-schemas) has been initially created to host the API specification for the NLP Sandbox Data Nodes. We have then created this repository in an effort to centralize all the API specifications, thus enabling to define Components and Paths that can be reused in more than one APIs.

## Objectives

- [ ] Create a PR to integrate the contributions made to data2health/nlp-sandbox-data-node-schemas (George)
- [ ] Delete the repo data2health/nlp-sandbox-data-node-schemas (Thomas)

**Comment by tschaffter** [comment]
The folder to update is https://github.com/data2health/nlp-sandbox-schemas/tree/main/openapi/data-node

**Comment by gkowalski** [comment]
Done
