### ISSUE TITLE
Update the openapi.yaml file for new Notes results. 

### ISSUE THREAD

**Issue by gkowalski** [data2health/nlp-sandbox-schemas#21]
This includes the items attribute, result count and pagination 

{
  "count": 514,
  "items": [
    {
    }

**Comment by tschaffter** [comment]
Let's add the following properties to the response:

- `previous`: URL to the previous page
- `next`: URL to the next page

This way the client can easily iterate over the pages until `next` is empty.

**Comment by tschaffter** [comment]
In terms of the i2b2 implementation, it's OK to leave the value of `previous` and `next` empty until we allows the user to specify the size of the pages (enhancement).

**Comment by tschaffter** [comment]
Done
